### ISSUE TITLE
Algolia PHP Client upgrade to version 4.

### ISSUE THREAD

**Issue by tw2113** [WebDevStudios/wp-search-with-algolia#402]
This isn't something we need to get started on ASAP, as version 4 is only in beta, but I'm filing this in preparation for when we do decide to upgrade.

Based on the documentation link below, we will have some breaking changes coming with the new version, so we'll need to handle that at the time.

This also could potentially be a version WPSwA 4.0.x release, due to the client upgrade also being a major one

# Resources
https://api-clients-automation.netlify.app/docs/clients/introduction/
https://github.com/algolia/algoliasearch-client-php/tree/next/

**Comment by graham73may** [comment]
Currently seeing this in my Algolia account under monitoring:

Algolia for PHP 3.3.2 ([4.8.1 available](https://github.com/algolia/algoliasearch-client-php?utm_medium=page_link&utm_source=dashboard))

Is there any news on if there's a plan to upgrade the Algolia PHP Client?

**Comment by tw2113** [comment]
No news at the exact moment, it's going to be something we need to rigorously test and confirm compatibility, so it's not going to be an overnight change.

**Comment by tw2113** [comment]
PHP Client 4.x has been out of Beta since August 2024, so this is something we could move forward with.

https://github.com/algolia/algoliasearch-client-php

**Comment by tw2113** [comment]
Moving this to version 3.0 targeted release due to scope of possible breaking.

**Comment by AE-Rushit-Pandya** [comment]
@tw2113  We have received notice that PHP API Client v3.4.2 is sunsetting in Aug, 2026 and need to migrate. Is this something in queue to have sdk upgraded?

**Comment by gmay-sbx** [comment]
Say it ain't so! 

Checking... 
https://www.algolia.com/doc/libraries/sdk/versions#php

My take on this is: 

- Currently: v3.x is in a "Maintenance" or "Legacy" phase. It is still eligible for SLA until August 14, 2026.
- After August 2026: It becomes "Unsupported." It will still "work," but you are officially on your own.

**Comment by tw2113** [comment]
@AE-Rushit-Pandya @gmay-sbx 

Thanks for these notifications. Good to know that it'll still "work" so to speak, but the being on our own is definitely something to keep in mind.

Unsure how often it breaks in some way behind the scenes so to speak, or if it could potentially be pretty solid for awhile yet.

Added a link to the upgrade guide to the ticket description

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 Thank you for responding. We are using this plugin across multiple site to an huge extent. So I wanted to know if you are planning to upgrade the plugin with new SDK before/by Aug ? If not, it gives us an idea to look for alternatives.

**Comment by tw2113** [comment]
> [@tw2113](https://github.com/tw2113) Thank you for responding. We are using this plugin across multiple site to an huge extent. So I wanted to know if you are planning to upgrade the plugin with new SDK before/by Aug ? If not, it gives us an idea to look for alternatives.

I don't know of any alternatives at the moment that would integrate with how our plugin works + config etc. I have raised the topic internally with some urgency.

As @gmay-sbx mentioned, it'll still continue to work (for the time being), so if we get to September, your sites won't stop working stone cold. We'd just not be able to raise issues with Algolia if we happen to find bugs/issues.

We'll be reviewing more sooner than later.

**Comment by tw2113** [comment]
NEED TO KEEP IN MIND ANY CUSTOM INSTANTIATIONS OUTSIDE OF CORE PLUGIN

For example:

```
$algolia_plugin     = \Algolia_Plugin_Factory::create();
$synced_indices_ids = $algolia_plugin->get_settings()->get_synced_indices_ids();
$index_name_prefix  = $algolia_plugin->get_settings()->get_index_name_prefix();
$client             = $algolia_plugin->get_api()->get_client();
```
If we are changing internals, there will hopefully be less headache.

Definitely warrants a 3.0.0 major/breaking release risk.

**Comment by AE-Rushit-Pandya** [comment]
> > [@tw2113](https://github.com/tw2113) Thank you for responding. We are using this plugin across multiple site to an huge extent. So I wanted to know if you are planning to upgrade the plugin with new SDK before/by Aug ? If not, it gives us an idea to look for alternatives.
> 
> I don't know of any alternatives at the moment that would integrate with how our plugin works + config etc. I have raised the topic internally with some urgency.
> 
> As [@gmay-sbx](https://github.com/gmay-sbx) mentioned, it'll still continue to work (for the time being), so if we get to September, your sites won't stop working stone cold. We'd just not be able to raise issues with Algolia if we happen to find bugs/issues.
> 
> We'll be reviewing more sooner than later.

@tw2113 Sorry for checking again. Just wanted to real quick check if there is scope of updating plugin before August? I understand there wouldn't be any breaking changes if we don't have any update.

**Comment by tw2113** [comment]
@AE-Rushit-Pandya I know that I have https://github.com/WebDevStudios/wp-search-with-algolia/pull/552 started and is ripe for testing.

If you're interested and perhaps have a staging site that can be used for a bit, I can provide a version of the plugin with this update, as if it was acquired from WordPress.org.

I haven't managed to find any missed issues on my own testing as part of the upgrade process, at this point in time. However, you may have spots that unearth things that we could then fix up appropriately.

**Comment by gmay-sbx** [comment]
@tw2113 I'd be happy to test a new updated release on one of our sites too :+1:

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 That sounds great. We do have staging site and sandbox index to connect to and test it. Let me know how can I get beta build access.

**Comment by tw2113** [comment]
Please try out [wp-search-with-algolia-3.0.0-beta.zip](https://github.com/user-attachments/files/29014074/wp-search-with-algolia-3.0.0-beta.zip)

Let us know of any issues encountered. Hoping I got everything built out as expected and the new updates.

@gmay-sbx @AE-Rushit-Pandya

**Comment by gmay-sbx** [comment]
Thanks, will report back once I've had a chance to do some proper testing.

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 Thank you. I'll you know once I have this up running on our staging site and if see any issues. much appreciated.

**Comment by tw2113** [comment]
@gmay-sbx @AE-Rushit-Pandya Any noticed issues thus far?

**Comment by gmay-sbx** [comment]
Hi @tw2113 I'm scheduled to work on this week of 20th July. Will definitely report back 🙏

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 Apologies for the delay. I am scheduled to start work on this ASAP. I will let you know feedback by next week.

**Comment by tw2113** [comment]
In case wondering, the 2.12.0 release isn't needed to keep testing this out. That release is largely cosmetic in the WP Admin.

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 on one of the multisite, when I initially uploaded the beta version, it gave fatal error (listed below). But on immediate refresh, site loaded correctly with beta version activated and configured as previous version. Can you please check what can be done to avoid this fatal error?

[2026-07-07T11:04:39.670911+00:00] PHP Fatal error:  Uncaught Error: Class "WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Support\UserAgent" not found in plugins/wp-search-with-algolia/includes/factories/class-algolia-search-client-factory.php:60#012Stack trace:#012#0 /plugins/wp-search-with-algolia/includes/class-algolia-api.php(98): Algolia_Search_Client_Factory::create('XXXXXXX...', 'XXXXXXXXX...')#012#1 /plugins/wp-search-with-algolia/includes/class-algolia-api.php(69): Algolia_API->get_client()#012#2 /plugins/wp-search-with-algolia/includes/class-algolia-plugin.php(178): Algolia_API->is_reachable()#012#3 /wp-includes/class-wp-hook.php(341): Algolia_Plugin->load('')#012#4 /wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters(NULL, Array)#012#5 /wp-includes/plugin.php(522): WP_Hook->do_action(Array)#012#6 wp-settings.php(771): do_action('init')#012#7 /wp-config.php(132): require_once('/nas/content/li...')#012#8 wp-load.php(50): require_once('/nas/content/li...')#012#9 //wp-cron.php(46): require_once('/nas/content/li...')#012#10 {main}#012  thrown in /plugins/wp-search-with-algolia/includes/factories/class-algolia-search-client-factory.php on line 60

[2026-07-07T11:04:42.450295+00:00] PHP Fatal error:  Uncaught Error: Class "WebDevStudios\WPSWA\Algolia\AlgoliaSearch\Support\UserAgent" not found in /plugins/wp-search-with-algolia/includes/factories/class-algolia-search-client-factory.php:60#012Stack trace:#012#0 /plugins/wp-search-with-algolia/includes/class-algolia-api.php(98): Algolia_Search_Client_Factory::create('XXXXXXXX...', 'XXXXXXX...')#012#1 plugins/wp-search-with-algolia/includes/class-algolia-api.php(69): Algolia_API->get_client()#012#2 plugins/wp-search-with-algolia/includes/class-algolia-plugin.php(178): Algolia_API->is_reachable()#012#3 /wp-includes/class-wp-hook.php(341): Algolia_Plugin->load('')#012#4/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters(NULL, Array)#012#5 /wp-includes/plugin.php(522): WP_Hook->do_action(Array)#012#6 /wp-settings.php(771): do_action('init')#012#7 /wp-config.php(132): require_once('/nas/content/li...')#012#8 /wp-load.php(50): require_once('/nas/content/li...')#012#9 /wp-admin/admin.php(35): require_once('/nas/content/li...')#012#10 /wp-admin/network/admin.php(13): require_once('/nas/content/li...')#012#11 /wp-admin/network/plugins.php(11): require_once('/nas/content/li...')#012#12 {main}#012  thrown in /plugins/wp-search-with-algolia/includes/factories/class-algolia-search-client-factory.php on line 60

Other than that, beta version is working correctly on this multisite. I am gonna test one more site where we are using the plugin.

Please let me know if you need more info to debug above.

**Comment by tw2113** [comment]
Thanks for this. Will review that UserAgent part. I know that section was interesting to try and convert, and we can re-review/re-test.

**Comment by tw2113** [comment]
@AE-Rushit-Pandya not managing to recreate this issue so far. I've copied the zip file into installs that are brand new for having Algolia installed, and it activated without issue.

So, keeping it noted, but not sure it's going to be a widespread issue just yet.

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 Thanks for the update. I can try to replicate it again but can you please confirm if you tried on multisite install as well?

Also, one of my site was using internals that you posted here https://github.com/WebDevStudios/wp-search-with-algolia/issues/402#issuecomment-4522026782 and it was causing fatal error after beta install. Site was trying to get index settings. I have posted below before and after code.


Before
```php
       /**
	 * Get the native algolia index object.
	 *
	 * @return Algolia_Index|null
	 */
	private function get_native_index(): ?Algolia_Index {

		if ( ! $this->is_plugin_enabled( self::PLUGIN_PATH ) ) {
			return null;
		}

		$algolia         = Algolia_Plugin_Factory::create();
		$native_index_id = $algolia->get_settings()->get_native_search_index_id();
		return $algolia->get_index( $native_index_id );
	}


	/**
	 * We only intend to use the first index for this project, this simply returns its settings for use within the system...so that algolia interface can be used for settings.
	 *
	 * @return array
	 */
	public function get_native_index_settings(): array {

		$native_index = $this->get_native_index();

		if ( ! $native_index instanceof Algolia_Index ) {
			return [];
		}

		return $native_index->get_index()->getSettings() ?? []; // this is where fatal error occured since get_index is deprecated function and returns false instead of object.
	}
``` 
After
```php
         /**
	 * Get the native algolia index object.
	 *
	 * @return Algolia_Index|null
	 */
	private function get_native_index(): ?Algolia_Index {

		if ( ! $this->is_plugin_enabled( self::PLUGIN_PATH ) ) {
			return null;
		}

		$algolia         = Algolia_Plugin_Factory::create();
		$native_index_id = $algolia->get_settings()->get_native_search_index_id();
		return $algolia->get_index( $native_index_id );
	}


	/**
	 * We only intend to use the first index for this project, this simply returns its settings for use within the system...so that algolia interface can be used for settings.
	 *
	 * @return array
	 */
	public function get_native_index_settings(): array {
		$algolia = Algolia_Plugin_Factory::create();
		$client  = $algolia->get_api()->get_client();

		$native_index = $this->get_native_index();

		if ( ! $native_index instanceof Algolia_Index || ! $client ) {
                    return [];
                }
		
		$settings = $client->getSettings( $native_index->get_name() );
		return is_array( $settings ) ? $settings : [];
	}
``` 

I tested and I am able to retrieve the index settings using updated code $settings = $client->getSettings( $native_index->get_name() );. Let me know if that is how its supposed to be.

**Comment by tw2113** [comment]
> I can try to replicate it again but can you please confirm if you tried on multisite install as well?

Tried with both a single site, and a multisite, and I just tried with network activating too without error.

For your custom code fatal error, I believe that update is correct, based on https://www.algolia.com/doc/libraries/sdk/upgrade/php#update-settings-synonyms-and-rules

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 I think we are good on our side in terms of beta testing. I haven't able to replicate fatal error on install issue other than that one time. Do we know when this release/update be coming officially?

**Comment by tw2113** [comment]
I'd like to get this out before end of August at the latest, but I also know we just finally did 2.13.0 with the Autocomplete 1.x availability too. Trying to avoid bundling too many major changes back to back.

With a version of 3.0.0 being considered a backwards compatibility breaking version, I want to get other parts of similar consequence included as well.

I'll probably spend some time soon plotting that out.

**Comment by tw2113** [comment]
That said, great to hear that it's been otherwise smooth sailing with the upgrade.

**Comment by gmay-sbx** [comment]
Hi @tw2113, just to add that I've tested #552 on my client site and it's been totally fine. 

Indexing from admin - Fine
Indexing on save post - Fine
Save post hooks which fire and re-index WPML translations - Fine
Custom CLI commands to index post IDs or whole post types - Fine

InstantSearch.js also working fine in my templates, I haven't noticed an errors or broken functionality. 

Thanks for the heads up and letting me test this pre-release!

**Comment by tw2113** [comment]
I've merged this into the `release300` branch but am not closing this ticket quite yet.

Outside of a brief hiccup, everyone who has tested, has found zero issues, which is awesome.

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 can you please update thread when we have date for this release to be available?

**Comment by tw2113** [comment]
Hi @AE-Rushit-Pandya 

At this point in time, I'm no longer able to say with regards to official release time. I am no longer affiliated with WebDevStudios.

@thatmitchcanter I'm willing to still help out however which ways possible, even if just helping facilitate a smaller scoped 3.0.0 release to handle PHP SDK updates.

**Comment by AE-Rushit-Pandya** [comment]
@tw2113 - Thank you so much for all the help so far.

@thatmitchcanter anyway you can provide some timeline on this release please?
